import './sass/main.scss';
import './js/menu-mobile.js';
import './js/menu.js';
//=========layout===============
// images
import './images/main/contact-us/phone-bg-mobile.png';
// import './images/main/contact-us/phone-bg-mobile.webp';
import './images/main/contact-us/phone-bg-mobile@1.5x.png';
// import './images/main/contact-us/phone-bg-mobile@1.5x.webp';
import './images/main/contact-us/phone-bg-mobile@2x.png';
// import './images/main/contact-us/phone-bg-mobile@2x.webp';
import './images/main/lawyers-in-busines/lawyers-in-busines-mobile.jpg';
import './images/main/lawyers-in-busines/lawyers-in-busines-mobile.jpg';
import './images/main/lawyers-in-busines/lawyers-in-busines-mobile@1.5x.jpg';
import './images/main/lawyers-in-busines/lawyers-in-busines-mobile@2x.jpg';
import './images/main/lawyers-in-busines/lawyers-in-busines_bg-mobile.png';
import './images/main/lawyers-in-busines/lawyers-in-busines_bg-mobile@1.5x.png';
import './images/main/lawyers-in-busines/lawyers-in-busines_bg-mobile@2x.png';
import './images/main/questions/justice_statue-mobile.png';
// import './images/main/questions/justice_statue-mobile.webp';
import './images/main/questions/justice_statue-mobile@1.5x.png';
// import './images/main/questions/justice_statue-mobile@1.5x.webp';
import './images/main/questions/justice_statue-mobile@2x.png';
// import './images/main/questions/justice_statue-mobile@2x.webp';
import './images/main/questions/justice_statue_backgroumd-mobile.png';
import './images/main/questions/justice_statue_backgroumd-mobile@1.5x.png';
import './images/main/questions/justice_statue_backgroumd-mobile@2x.png';
import './images/svg/checkbox-checked.svg';
import './images/svg/delivery.svg';
import './images/svg/li-circle.svg';
import './images/svg/low-price.svg';
import './images/svg/network.svg';
import './images/svg/phone-calling.svg';
import './images/svg/sertificates.svg';
import './images/svg/user.svg';
import './images/icons.svg';
import './images/style.css';
